# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - refs/tags/*
    - dev
    - develop
jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '3.0.100'
    - powershell: .\build.ps1
      displayName: 'Run build.ps1'